//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.application.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class universaldbEntities : DbContext
    {
        public universaldbEntities()
            : base("name=universaldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App_T_Department> App_T_Department { get; set; }
        public virtual DbSet<App_T_Employee> App_T_Employee { get; set; }
    
        public virtual ObjectResult<App_SP_EmployeeGet_Result> App_SP_EmployeeGet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SP_EmployeeGet_Result>("App_SP_EmployeeGet");
        }
    }
}
